---
- name: config_php5 | installing php5 (if-enabled)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-cli
    - php5-fpm
  when: >
        ansible_os_family == "Debian"

- name: config_php5 | installing php5 (if-enabled)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - lighttpd-fastcgi
    - php
    - php-cli
    - php-fpm
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora"

- name: config_php5 | installing php5 (if-enabled)
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - lighttpd-fastcgi
    - php
    - php-cli
    - php-fpm
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution == "Fedora"

- name: config_php5 | configuring php5
  template:
    src: "etc/php5/fpm/php.ini.j2"
    dest: "/etc/php5/fpm/php.ini"
    owner: root
    group: root
    mode: 0644
  when: >
        ansible_os_family == "Debian"

- name: config_php5 | configuring php5
  template:
    src: "etc/php5/fpm/php.ini.j2"
    dest: "/etc/php.ini"
    owner: root
    group: root
    mode: 0644
  when: >
        ansible_os_family == "RedHat"

- name: config_php5 | configuring php5
  template:
    src: "etc/php-fpm.d/www.conf.j2"
    dest: "/etc/php-fpm.d/www.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php-fpm
  when: >
        ansible_os_family == "RedHat"

- name: config_php5 | ensuring php-fpm is enabled on boot and started
  service:
    name: "php-fpm"
    state: started
    enabled: yes
  when: >
        ansible_os_family == "RedHat"

- name: config_php5 | configuring lighttpd for php5
  template:
    src: "etc/lighttpd/conf-available/15-fastcgi-php.conf.j2"
    dest: "/etc/lighttpd/conf-available/15-fastcgi-php.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart lighttpd
  when: >
        ansible_os_family == "Debian"

- name: config_php5 | enabling php5 modules for lighttpd
  command: "{{ item.cmd }}"
  args:
    creates: "{{ item.creates }}"
  with_items:
    - cmd: 'lighttpd-enable-mod fastcgi'
      creates: '/etc/lighttpd/conf-enabled/10-fastcgi.conf'
    - cmd: 'lighttpd-enable-mod fastcgi-php'
      creates: '/etc/lighttpd/conf-enabled/15-fastcgi-php.conf'
  notify:
    - restart lighttpd
  when: >
        ansible_os_family == "Debian"

- name: config_php5 | installing php5 xcache (if-enabled)
  apt:
    name: "php5-xcache"
    state: present
  notify:
    - restart lighttpd
  when: >
        ansible_os_family == "Debian" and
        lighttpd_enable_php5_xcache

- name: config_php5 | installing php xcache (if-enabled)
  yum:
    name: "{{ item }}"
    state: present
  notify:
    - restart lighttpd
  with_items:
    - php-xcache
    - xcache-admin
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora" and
        lighttpd_enable_php5_xcache

- name: config_php5 | installing php xcache (if-enabled)
  dnf:
    name: "{{ item }}"
    state: present
  notify:
    - restart lighttpd
  with_items:
    - php-xcache
    - xcache-admin
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution == "Fedora" and
        lighttpd_enable_php5_xcache
