---
# tasks file for ansible-lighttpd
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: config_lighttpd.yml
  when: config_lighttpd

- include: config_php5.yml
  when: lighttpd_enable_php5
